// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3mE8sf4U3Hb5SQGnnWnbFfqKiK2sWGU4',
    appId: '1:14498850066:web:c5c47887a903fc55e83fcb',
    messagingSenderId: '14498850066',
    projectId: 'fruit-hub-17e40',
    authDomain: 'fruit-hub-17e40.firebaseapp.com',
    storageBucket: 'fruit-hub-17e40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANUd9MEO-p48Qd8pbHQg3gTM_i0fcsOEE',
    appId: '1:14498850066:android:8cf2fe28397a2588e83fcb',
    messagingSenderId: '14498850066',
    projectId: 'fruit-hub-17e40',
    storageBucket: 'fruit-hub-17e40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASzzj81pdljM_lEZ8tetVJ1cZTIoy8vZE',
    appId: '1:14498850066:ios:1ddd3f8e39189e81e83fcb',
    messagingSenderId: '14498850066',
    projectId: 'fruit-hub-17e40',
    storageBucket: 'fruit-hub-17e40.firebasestorage.app',
    androidClientId: '14498850066-epcfoqd1h6eghcusj0pascn2pl9fbe2o.apps.googleusercontent.com',
    iosClientId: '14498850066-kmcf4stlee5cgmbdt7c4g6nltpibrhre.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );
}
